### ISSUE TITLE
error

### ISSUE THREAD

**Issue by djjemsion31** [HarutoHiroki/alexflipnote.js#6]
i keep getting this 
/lib/connection.js:832:32)
    at /rbd/pnpm-volume/7a4c6eb2-9d49-4b2d-8b6b-4dc7187eff24/node_modules/.registry.npmjs.org/mongoose/5.11.11/node_modules/mongoose/lib/index.js:345:10
    at promiseOrCallback (/rbd/pnpm-volume/7a4c6eb2-9d49-4b2d-8b6b-4dc7187eff24/node_modules/.registry.npmjs.org/mongoose/5.11.11/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Mongoose._promiseOrCallback (/rbd/pnpm-volume/7a4c6eb2-9d49-4b2d-8b6b-4dc7187eff24/node_modules/.registry.npmjs.org/mongoose/5.11.11/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/rbd/pnpm-volume/7a4c6eb2-9d49-4b2d-8b6b-4dc7187eff24/node_modules/.registry.npmjs.org/mongoose/5.11.11/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/app/index.js:51:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11 {
  message: 'connect ECONNREFUSED 127.0.0.1:27017',
  reason: TopologyDescription {
    type: 'Unknown',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

**Comment by HarutoHiroki** [comment]
Are you sure you've read the README.md file and follow all the steps in there? Because it seems like you haven't created your mongoDB database.
