### ISSUE TITLE
error when using image endpoints

### ISSUE THREAD

**Issue by skiddy-skidder** [HarutoHiroki/alexflipnote.js#7]
I'm getting this error when using an image endpoint

(node:29108) UnhandledPromiseRejectionWarning: TypeError: The resource must be a string or Buffer.
    at ClientDataResolver.resolveFile (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/client/ClientDataResolver.js:278:27)
    at Promise.all.options.files.map.file (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:173:30)
    at Array.map (<anonymous>)
    at TextChannel.send (/rbd/pnpm-volume/b61a9277-9cdc-4324-bb15-59d6b9a53b28/node_modules/.registry.npmjs.org/discord.js/11.6.4/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:40)
at Object.exports.run (/app/functions/commands/deepfry.js:27:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:29108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

this is my code:

```js
const fetch = require("node-fetch")
const Discord = require("discord.js")

exports.run = async (client, msg, args, main_color, some_random_api_url, alexclient) => {
  
  try {
    
  let avatar_url = '';
	let user = '';
	if (!args[1]) {
		user = msg.author;
		avatar_url = user.displayAvatarURL;
	} else if (args[1].match(/^<@!?(\d+)>$/)) {
		const matches = args[1].match(/^<@!?(\d+)>$/);
		const id = matches[1];
		user = new Discord.User(client, client.users.get(id));

		avatar_url = user.displayAvatarURL;
	} else return msg.reply('you provided an invalid user.');
    
let link = await alexclient.image.communist(avatar_url)

msg.channel.send({files: [{ attachment: link }]});
      
  } catch (e) {
    console.log(e);
  }
};

**Comment by HarutoHiroki** [comment]
console log the `link` variable, you will see why

**Comment by skiddy-skidder** [comment]
{ code: 400,
  name: 'Bad Request',
  description: 'You must provide an image' }


but I did...

**Comment by HarutoHiroki** [comment]
`.displayAvatarUrl` isn't a thing
however, `.displayAvatarUrl()`, is
please read through your code before making an issue

**Comment by HarutoHiroki** [comment]
*`.displayAvatarURL()`

**Comment by skiddy-skidder** [comment]
> *`.displayAvatarURL()`

im using discord.js v11, it's .displayAvatarURL()

i know it's better to use v12 but I can't be asked to update yet. v11 shouldn't be the problem tho
